version: '3.3'
services:
  estacionamentodb:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - estacionamentodb:/var/lib/mysql
# Names our volume
volumes:
  estacionamentodb: